//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MillionaireWinnerPicker.ADService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuthenticationServiceSoap", Namespace="http://tempuri.org/")]
    public partial class AuthenticationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUserAdStaffIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserAdFullDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserAdGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserFinacleDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTellerFinacleTillAccountsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserAccountOfficerDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserDsaDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBranchOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetZoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStaffIDWithUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStaffGroupWithUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateTokenDigipassOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserAdFullDetailsWLoginNameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AuthenticationService() {
            this.Url = global::MillionaireWinnerPicker.Properties.Settings.Default.MillionaireWinnerPicker_ADService_AuthenticationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUserAdStaffIDCompletedEventHandler GetUserAdStaffIDCompleted;
        
        /// <remarks/>
        public event GetUserAdFullDetailsCompletedEventHandler GetUserAdFullDetailsCompleted;
        
        /// <remarks/>
        public event GetUserAdGroupsCompletedEventHandler GetUserAdGroupsCompleted;
        
        /// <remarks/>
        public event GetUserFinacleDetailsCompletedEventHandler GetUserFinacleDetailsCompleted;
        
        /// <remarks/>
        public event GetTellerFinacleTillAccountsCompletedEventHandler GetTellerFinacleTillAccountsCompleted;
        
        /// <remarks/>
        public event GetUserAccountOfficerDetailsCompletedEventHandler GetUserAccountOfficerDetailsCompleted;
        
        /// <remarks/>
        public event GetUserDsaDetailsCompletedEventHandler GetUserDsaDetailsCompleted;
        
        /// <remarks/>
        public event GetBranchCompletedEventHandler GetBranchCompleted;
        
        /// <remarks/>
        public event GetZoneCompletedEventHandler GetZoneCompleted;
        
        /// <remarks/>
        public event GetStaffIDWithUserNameCompletedEventHandler GetStaffIDWithUserNameCompleted;
        
        /// <remarks/>
        public event GetStaffGroupWithUserNameCompletedEventHandler GetStaffGroupWithUserNameCompleted;
        
        /// <remarks/>
        public event AuthenticateTokenCompletedEventHandler AuthenticateTokenCompleted;
        
        /// <remarks/>
        public event AuthenticateTokenDigipassCompletedEventHandler AuthenticateTokenDigipassCompleted;
        
        /// <remarks/>
        public event ResetTokenCompletedEventHandler ResetTokenCompleted;
        
        /// <remarks/>
        public event GetUserAdFullDetailsWLoginNameCompletedEventHandler GetUserAdFullDetailsWLoginNameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserAdStaffID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserAdStaffID(string LoginName, string Password, string AppID, string AppKey) {
            object[] results = this.Invoke("GetUserAdStaffID", new object[] {
                        LoginName,
                        Password,
                        AppID,
                        AppKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserAdStaffIDAsync(string LoginName, string Password, string AppID, string AppKey) {
            this.GetUserAdStaffIDAsync(LoginName, Password, AppID, AppKey, null);
        }
        
        /// <remarks/>
        public void GetUserAdStaffIDAsync(string LoginName, string Password, string AppID, string AppKey, object userState) {
            if ((this.GetUserAdStaffIDOperationCompleted == null)) {
                this.GetUserAdStaffIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserAdStaffIDOperationCompleted);
            }
            this.InvokeAsync("GetUserAdStaffID", new object[] {
                        LoginName,
                        Password,
                        AppID,
                        AppKey}, this.GetUserAdStaffIDOperationCompleted, userState);
        }
        
        private void OnGetUserAdStaffIDOperationCompleted(object arg) {
            if ((this.GetUserAdStaffIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserAdStaffIDCompleted(this, new GetUserAdStaffIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserAdFullDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserAdDetails GetUserAdFullDetails(string LoginName, string Password, string AppID, string AppKey) {
            object[] results = this.Invoke("GetUserAdFullDetails", new object[] {
                        LoginName,
                        Password,
                        AppID,
                        AppKey});
            return ((UserAdDetails)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserAdFullDetailsAsync(string LoginName, string Password, string AppID, string AppKey) {
            this.GetUserAdFullDetailsAsync(LoginName, Password, AppID, AppKey, null);
        }
        
        /// <remarks/>
        public void GetUserAdFullDetailsAsync(string LoginName, string Password, string AppID, string AppKey, object userState) {
            if ((this.GetUserAdFullDetailsOperationCompleted == null)) {
                this.GetUserAdFullDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserAdFullDetailsOperationCompleted);
            }
            this.InvokeAsync("GetUserAdFullDetails", new object[] {
                        LoginName,
                        Password,
                        AppID,
                        AppKey}, this.GetUserAdFullDetailsOperationCompleted, userState);
        }
        
        private void OnGetUserAdFullDetailsOperationCompleted(object arg) {
            if ((this.GetUserAdFullDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserAdFullDetailsCompleted(this, new GetUserAdFullDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserAdGroups", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserAdGroups(string LoginName, string Password, string AppID, string AppKey) {
            object[] results = this.Invoke("GetUserAdGroups", new object[] {
                        LoginName,
                        Password,
                        AppID,
                        AppKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserAdGroupsAsync(string LoginName, string Password, string AppID, string AppKey) {
            this.GetUserAdGroupsAsync(LoginName, Password, AppID, AppKey, null);
        }
        
        /// <remarks/>
        public void GetUserAdGroupsAsync(string LoginName, string Password, string AppID, string AppKey, object userState) {
            if ((this.GetUserAdGroupsOperationCompleted == null)) {
                this.GetUserAdGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserAdGroupsOperationCompleted);
            }
            this.InvokeAsync("GetUserAdGroups", new object[] {
                        LoginName,
                        Password,
                        AppID,
                        AppKey}, this.GetUserAdGroupsOperationCompleted, userState);
        }
        
        private void OnGetUserAdGroupsOperationCompleted(object arg) {
            if ((this.GetUserAdGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserAdGroupsCompleted(this, new GetUserAdGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserFinacleDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserFinacleDetails GetUserFinacleDetails(string StaffID, string AppID, string AppKey) {
            object[] results = this.Invoke("GetUserFinacleDetails", new object[] {
                        StaffID,
                        AppID,
                        AppKey});
            return ((UserFinacleDetails)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserFinacleDetailsAsync(string StaffID, string AppID, string AppKey) {
            this.GetUserFinacleDetailsAsync(StaffID, AppID, AppKey, null);
        }
        
        /// <remarks/>
        public void GetUserFinacleDetailsAsync(string StaffID, string AppID, string AppKey, object userState) {
            if ((this.GetUserFinacleDetailsOperationCompleted == null)) {
                this.GetUserFinacleDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserFinacleDetailsOperationCompleted);
            }
            this.InvokeAsync("GetUserFinacleDetails", new object[] {
                        StaffID,
                        AppID,
                        AppKey}, this.GetUserFinacleDetailsOperationCompleted, userState);
        }
        
        private void OnGetUserFinacleDetailsOperationCompleted(object arg) {
            if ((this.GetUserFinacleDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserFinacleDetailsCompleted(this, new GetUserFinacleDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTellerFinacleTillAccounts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TillAccount[] GetTellerFinacleTillAccounts(string StaffID, string AppID, string AppKey) {
            object[] results = this.Invoke("GetTellerFinacleTillAccounts", new object[] {
                        StaffID,
                        AppID,
                        AppKey});
            return ((TillAccount[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTellerFinacleTillAccountsAsync(string StaffID, string AppID, string AppKey) {
            this.GetTellerFinacleTillAccountsAsync(StaffID, AppID, AppKey, null);
        }
        
        /// <remarks/>
        public void GetTellerFinacleTillAccountsAsync(string StaffID, string AppID, string AppKey, object userState) {
            if ((this.GetTellerFinacleTillAccountsOperationCompleted == null)) {
                this.GetTellerFinacleTillAccountsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTellerFinacleTillAccountsOperationCompleted);
            }
            this.InvokeAsync("GetTellerFinacleTillAccounts", new object[] {
                        StaffID,
                        AppID,
                        AppKey}, this.GetTellerFinacleTillAccountsOperationCompleted, userState);
        }
        
        private void OnGetTellerFinacleTillAccountsOperationCompleted(object arg) {
            if ((this.GetTellerFinacleTillAccountsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTellerFinacleTillAccountsCompleted(this, new GetTellerFinacleTillAccountsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserAccountOfficerDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserAccountOfficerDetails GetUserAccountOfficerDetails(string StaffID, string AppID, string AppKey) {
            object[] results = this.Invoke("GetUserAccountOfficerDetails", new object[] {
                        StaffID,
                        AppID,
                        AppKey});
            return ((UserAccountOfficerDetails)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserAccountOfficerDetailsAsync(string StaffID, string AppID, string AppKey) {
            this.GetUserAccountOfficerDetailsAsync(StaffID, AppID, AppKey, null);
        }
        
        /// <remarks/>
        public void GetUserAccountOfficerDetailsAsync(string StaffID, string AppID, string AppKey, object userState) {
            if ((this.GetUserAccountOfficerDetailsOperationCompleted == null)) {
                this.GetUserAccountOfficerDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserAccountOfficerDetailsOperationCompleted);
            }
            this.InvokeAsync("GetUserAccountOfficerDetails", new object[] {
                        StaffID,
                        AppID,
                        AppKey}, this.GetUserAccountOfficerDetailsOperationCompleted, userState);
        }
        
        private void OnGetUserAccountOfficerDetailsOperationCompleted(object arg) {
            if ((this.GetUserAccountOfficerDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserAccountOfficerDetailsCompleted(this, new GetUserAccountOfficerDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserDsaDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserDsaDetails GetUserDsaDetails(string DsaBrokerCode, string AppID, string AppKey) {
            object[] results = this.Invoke("GetUserDsaDetails", new object[] {
                        DsaBrokerCode,
                        AppID,
                        AppKey});
            return ((UserDsaDetails)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserDsaDetailsAsync(string DsaBrokerCode, string AppID, string AppKey) {
            this.GetUserDsaDetailsAsync(DsaBrokerCode, AppID, AppKey, null);
        }
        
        /// <remarks/>
        public void GetUserDsaDetailsAsync(string DsaBrokerCode, string AppID, string AppKey, object userState) {
            if ((this.GetUserDsaDetailsOperationCompleted == null)) {
                this.GetUserDsaDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserDsaDetailsOperationCompleted);
            }
            this.InvokeAsync("GetUserDsaDetails", new object[] {
                        DsaBrokerCode,
                        AppID,
                        AppKey}, this.GetUserDsaDetailsOperationCompleted, userState);
        }
        
        private void OnGetUserDsaDetailsOperationCompleted(object arg) {
            if ((this.GetUserDsaDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserDsaDetailsCompleted(this, new GetUserDsaDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBranch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Branch[] GetBranch(string AppID, string AppKey) {
            object[] results = this.Invoke("GetBranch", new object[] {
                        AppID,
                        AppKey});
            return ((Branch[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBranchAsync(string AppID, string AppKey) {
            this.GetBranchAsync(AppID, AppKey, null);
        }
        
        /// <remarks/>
        public void GetBranchAsync(string AppID, string AppKey, object userState) {
            if ((this.GetBranchOperationCompleted == null)) {
                this.GetBranchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBranchOperationCompleted);
            }
            this.InvokeAsync("GetBranch", new object[] {
                        AppID,
                        AppKey}, this.GetBranchOperationCompleted, userState);
        }
        
        private void OnGetBranchOperationCompleted(object arg) {
            if ((this.GetBranchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBranchCompleted(this, new GetBranchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetZone", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Zone[] GetZone(string AppID, string AppKey) {
            object[] results = this.Invoke("GetZone", new object[] {
                        AppID,
                        AppKey});
            return ((Zone[])(results[0]));
        }
        
        /// <remarks/>
        public void GetZoneAsync(string AppID, string AppKey) {
            this.GetZoneAsync(AppID, AppKey, null);
        }
        
        /// <remarks/>
        public void GetZoneAsync(string AppID, string AppKey, object userState) {
            if ((this.GetZoneOperationCompleted == null)) {
                this.GetZoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetZoneOperationCompleted);
            }
            this.InvokeAsync("GetZone", new object[] {
                        AppID,
                        AppKey}, this.GetZoneOperationCompleted, userState);
        }
        
        private void OnGetZoneOperationCompleted(object arg) {
            if ((this.GetZoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetZoneCompleted(this, new GetZoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStaffIDWithUserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetStaffIDWithUserName(string LoginName, string AppID, string AppKey) {
            object[] results = this.Invoke("GetStaffIDWithUserName", new object[] {
                        LoginName,
                        AppID,
                        AppKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStaffIDWithUserNameAsync(string LoginName, string AppID, string AppKey) {
            this.GetStaffIDWithUserNameAsync(LoginName, AppID, AppKey, null);
        }
        
        /// <remarks/>
        public void GetStaffIDWithUserNameAsync(string LoginName, string AppID, string AppKey, object userState) {
            if ((this.GetStaffIDWithUserNameOperationCompleted == null)) {
                this.GetStaffIDWithUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStaffIDWithUserNameOperationCompleted);
            }
            this.InvokeAsync("GetStaffIDWithUserName", new object[] {
                        LoginName,
                        AppID,
                        AppKey}, this.GetStaffIDWithUserNameOperationCompleted, userState);
        }
        
        private void OnGetStaffIDWithUserNameOperationCompleted(object arg) {
            if ((this.GetStaffIDWithUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStaffIDWithUserNameCompleted(this, new GetStaffIDWithUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStaffGroupWithUserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetStaffGroupWithUserName(string LoginName, string AppID, string AppKey) {
            object[] results = this.Invoke("GetStaffGroupWithUserName", new object[] {
                        LoginName,
                        AppID,
                        AppKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStaffGroupWithUserNameAsync(string LoginName, string AppID, string AppKey) {
            this.GetStaffGroupWithUserNameAsync(LoginName, AppID, AppKey, null);
        }
        
        /// <remarks/>
        public void GetStaffGroupWithUserNameAsync(string LoginName, string AppID, string AppKey, object userState) {
            if ((this.GetStaffGroupWithUserNameOperationCompleted == null)) {
                this.GetStaffGroupWithUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStaffGroupWithUserNameOperationCompleted);
            }
            this.InvokeAsync("GetStaffGroupWithUserName", new object[] {
                        LoginName,
                        AppID,
                        AppKey}, this.GetStaffGroupWithUserNameOperationCompleted, userState);
        }
        
        private void OnGetStaffGroupWithUserNameOperationCompleted(object arg) {
            if ((this.GetStaffGroupWithUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStaffGroupWithUserNameCompleted(this, new GetStaffGroupWithUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AuthenticateToken", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AuthenticateToken(string staffId, string tokenCode, string AppID, string AppKey) {
            object[] results = this.Invoke("AuthenticateToken", new object[] {
                        staffId,
                        tokenCode,
                        AppID,
                        AppKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateTokenAsync(string staffId, string tokenCode, string AppID, string AppKey) {
            this.AuthenticateTokenAsync(staffId, tokenCode, AppID, AppKey, null);
        }
        
        /// <remarks/>
        public void AuthenticateTokenAsync(string staffId, string tokenCode, string AppID, string AppKey, object userState) {
            if ((this.AuthenticateTokenOperationCompleted == null)) {
                this.AuthenticateTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateTokenOperationCompleted);
            }
            this.InvokeAsync("AuthenticateToken", new object[] {
                        staffId,
                        tokenCode,
                        AppID,
                        AppKey}, this.AuthenticateTokenOperationCompleted, userState);
        }
        
        private void OnAuthenticateTokenOperationCompleted(object arg) {
            if ((this.AuthenticateTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateTokenCompleted(this, new AuthenticateTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AuthenticateTokenDigipass", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AuthenticateTokenDigipass(string Username, string tokenCode, string AppID, string AppKey) {
            object[] results = this.Invoke("AuthenticateTokenDigipass", new object[] {
                        Username,
                        tokenCode,
                        AppID,
                        AppKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateTokenDigipassAsync(string Username, string tokenCode, string AppID, string AppKey) {
            this.AuthenticateTokenDigipassAsync(Username, tokenCode, AppID, AppKey, null);
        }
        
        /// <remarks/>
        public void AuthenticateTokenDigipassAsync(string Username, string tokenCode, string AppID, string AppKey, object userState) {
            if ((this.AuthenticateTokenDigipassOperationCompleted == null)) {
                this.AuthenticateTokenDigipassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateTokenDigipassOperationCompleted);
            }
            this.InvokeAsync("AuthenticateTokenDigipass", new object[] {
                        Username,
                        tokenCode,
                        AppID,
                        AppKey}, this.AuthenticateTokenDigipassOperationCompleted, userState);
        }
        
        private void OnAuthenticateTokenDigipassOperationCompleted(object arg) {
            if ((this.AuthenticateTokenDigipassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateTokenDigipassCompleted(this, new AuthenticateTokenDigipassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResetToken", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ResetToken(string StaffID, string AppID, string AppKey) {
            object[] results = this.Invoke("ResetToken", new object[] {
                        StaffID,
                        AppID,
                        AppKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ResetTokenAsync(string StaffID, string AppID, string AppKey) {
            this.ResetTokenAsync(StaffID, AppID, AppKey, null);
        }
        
        /// <remarks/>
        public void ResetTokenAsync(string StaffID, string AppID, string AppKey, object userState) {
            if ((this.ResetTokenOperationCompleted == null)) {
                this.ResetTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetTokenOperationCompleted);
            }
            this.InvokeAsync("ResetToken", new object[] {
                        StaffID,
                        AppID,
                        AppKey}, this.ResetTokenOperationCompleted, userState);
        }
        
        private void OnResetTokenOperationCompleted(object arg) {
            if ((this.ResetTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetTokenCompleted(this, new ResetTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserAdFullDetailsWLoginName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserAdDetails GetUserAdFullDetailsWLoginName(string LoginName, string AppID, string AppKey) {
            object[] results = this.Invoke("GetUserAdFullDetailsWLoginName", new object[] {
                        LoginName,
                        AppID,
                        AppKey});
            return ((UserAdDetails)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserAdFullDetailsWLoginNameAsync(string LoginName, string AppID, string AppKey) {
            this.GetUserAdFullDetailsWLoginNameAsync(LoginName, AppID, AppKey, null);
        }
        
        /// <remarks/>
        public void GetUserAdFullDetailsWLoginNameAsync(string LoginName, string AppID, string AppKey, object userState) {
            if ((this.GetUserAdFullDetailsWLoginNameOperationCompleted == null)) {
                this.GetUserAdFullDetailsWLoginNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserAdFullDetailsWLoginNameOperationCompleted);
            }
            this.InvokeAsync("GetUserAdFullDetailsWLoginName", new object[] {
                        LoginName,
                        AppID,
                        AppKey}, this.GetUserAdFullDetailsWLoginNameOperationCompleted, userState);
        }
        
        private void OnGetUserAdFullDetailsWLoginNameOperationCompleted(object arg) {
            if ((this.GetUserAdFullDetailsWLoginNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserAdFullDetailsWLoginNameCompleted(this, new GetUserAdFullDetailsWLoginNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserAdDetails {
        
        private string staffIDField;
        
        private string groupsField;
        
        private string emailField;
        
        private string staffNameField;
        
        private string displayNameField;
        
        private string departmentField;
        
        private string mobileNoField;
        
        private string managerNameField;
        
        private string managerDepartmentField;
        
        private string responseField;
        
        private string responseMessageField;
        
        /// <remarks/>
        public string StaffID {
            get {
                return this.staffIDField;
            }
            set {
                this.staffIDField = value;
            }
        }
        
        /// <remarks/>
        public string Groups {
            get {
                return this.groupsField;
            }
            set {
                this.groupsField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string StaffName {
            get {
                return this.staffNameField;
            }
            set {
                this.staffNameField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string MobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
            }
        }
        
        /// <remarks/>
        public string ManagerName {
            get {
                return this.managerNameField;
            }
            set {
                this.managerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ManagerDepartment {
            get {
                return this.managerDepartmentField;
            }
            set {
                this.managerDepartmentField = value;
            }
        }
        
        /// <remarks/>
        public string Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Zone {
        
        private string zoneCodeField;
        
        private string zoneNameField;
        
        private string regionCodeField;
        
        /// <remarks/>
        public string ZoneCode {
            get {
                return this.zoneCodeField;
            }
            set {
                this.zoneCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ZoneName {
            get {
                return this.zoneNameField;
            }
            set {
                this.zoneNameField = value;
            }
        }
        
        /// <remarks/>
        public string RegionCode {
            get {
                return this.regionCodeField;
            }
            set {
                this.regionCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Branch {
        
        private string branchCodeField;
        
        private string branchNameField;
        
        private string zoneCodeField;
        
        private string zoneCodeOpsField;
        
        private string csmEmailField;
        
        private string branchManagerEmailField;
        
        /// <remarks/>
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BranchName {
            get {
                return this.branchNameField;
            }
            set {
                this.branchNameField = value;
            }
        }
        
        /// <remarks/>
        public string ZoneCode {
            get {
                return this.zoneCodeField;
            }
            set {
                this.zoneCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ZoneCodeOps {
            get {
                return this.zoneCodeOpsField;
            }
            set {
                this.zoneCodeOpsField = value;
            }
        }
        
        /// <remarks/>
        public string CsmEmail {
            get {
                return this.csmEmailField;
            }
            set {
                this.csmEmailField = value;
            }
        }
        
        /// <remarks/>
        public string BranchManagerEmail {
            get {
                return this.branchManagerEmailField;
            }
            set {
                this.branchManagerEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserDsaDetails {
        
        private string employeeCodeField;
        
        private string userIDField;
        
        private string employeeNameField;
        
        private string accountOfficerCodeField;
        
        private string dsaBrokerCodeField;
        
        private string branchField;
        
        private string roleTypeField;
        
        /// <remarks/>
        public string EmployeeCode {
            get {
                return this.employeeCodeField;
            }
            set {
                this.employeeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string EmployeeName {
            get {
                return this.employeeNameField;
            }
            set {
                this.employeeNameField = value;
            }
        }
        
        /// <remarks/>
        public string AccountOfficerCode {
            get {
                return this.accountOfficerCodeField;
            }
            set {
                this.accountOfficerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DsaBrokerCode {
            get {
                return this.dsaBrokerCodeField;
            }
            set {
                this.dsaBrokerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Branch {
            get {
                return this.branchField;
            }
            set {
                this.branchField = value;
            }
        }
        
        /// <remarks/>
        public string RoleType {
            get {
                return this.roleTypeField;
            }
            set {
                this.roleTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserAccountOfficerDetails {
        
        private string staffIDField;
        
        private string accountOfficerField;
        
        private string accountOfficerCodeField;
        
        private string sbuCodeField;
        
        private string branchCodeField;
        
        private string regionCodeField;
        
        private string zoneCodeField;
        
        /// <remarks/>
        public string StaffID {
            get {
                return this.staffIDField;
            }
            set {
                this.staffIDField = value;
            }
        }
        
        /// <remarks/>
        public string AccountOfficer {
            get {
                return this.accountOfficerField;
            }
            set {
                this.accountOfficerField = value;
            }
        }
        
        /// <remarks/>
        public string AccountOfficerCode {
            get {
                return this.accountOfficerCodeField;
            }
            set {
                this.accountOfficerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SbuCode {
            get {
                return this.sbuCodeField;
            }
            set {
                this.sbuCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RegionCode {
            get {
                return this.regionCodeField;
            }
            set {
                this.regionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ZoneCode {
            get {
                return this.zoneCodeField;
            }
            set {
                this.zoneCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TillAccount {
        
        private string tELLER_TILLField;
        
        private string cURRENCYCODEField;
        
        private string bRANCHCODEField;
        
        private string staffIdField;
        
        /// <remarks/>
        public string TELLER_TILL {
            get {
                return this.tELLER_TILLField;
            }
            set {
                this.tELLER_TILLField = value;
            }
        }
        
        /// <remarks/>
        public string CURRENCYCODE {
            get {
                return this.cURRENCYCODEField;
            }
            set {
                this.cURRENCYCODEField = value;
            }
        }
        
        /// <remarks/>
        public string BRANCHCODE {
            get {
                return this.bRANCHCODEField;
            }
            set {
                this.bRANCHCODEField = value;
            }
        }
        
        /// <remarks/>
        public string StaffId {
            get {
                return this.staffIdField;
            }
            set {
                this.staffIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserFinacleDetails {
        
        private string staffIDField;
        
        private string finacleUserIDField;
        
        private string roleIDField;
        
        private string branchCodeField;
        
        private string genericRoleIDField;
        
        private string sOL_DESCField;
        
        /// <remarks/>
        public string StaffID {
            get {
                return this.staffIDField;
            }
            set {
                this.staffIDField = value;
            }
        }
        
        /// <remarks/>
        public string FinacleUserID {
            get {
                return this.finacleUserIDField;
            }
            set {
                this.finacleUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string RoleID {
            get {
                return this.roleIDField;
            }
            set {
                this.roleIDField = value;
            }
        }
        
        /// <remarks/>
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string GenericRoleID {
            get {
                return this.genericRoleIDField;
            }
            set {
                this.genericRoleIDField = value;
            }
        }
        
        /// <remarks/>
        public string SOL_DESC {
            get {
                return this.sOL_DESCField;
            }
            set {
                this.sOL_DESCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetUserAdStaffIDCompletedEventHandler(object sender, GetUserAdStaffIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserAdStaffIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserAdStaffIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetUserAdFullDetailsCompletedEventHandler(object sender, GetUserAdFullDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserAdFullDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserAdFullDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserAdDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserAdDetails)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetUserAdGroupsCompletedEventHandler(object sender, GetUserAdGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserAdGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserAdGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetUserFinacleDetailsCompletedEventHandler(object sender, GetUserFinacleDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserFinacleDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserFinacleDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserFinacleDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserFinacleDetails)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetTellerFinacleTillAccountsCompletedEventHandler(object sender, GetTellerFinacleTillAccountsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTellerFinacleTillAccountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTellerFinacleTillAccountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TillAccount[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TillAccount[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetUserAccountOfficerDetailsCompletedEventHandler(object sender, GetUserAccountOfficerDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserAccountOfficerDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserAccountOfficerDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserAccountOfficerDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserAccountOfficerDetails)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetUserDsaDetailsCompletedEventHandler(object sender, GetUserDsaDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserDsaDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserDsaDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserDsaDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserDsaDetails)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetBranchCompletedEventHandler(object sender, GetBranchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBranchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBranchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Branch[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Branch[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetZoneCompletedEventHandler(object sender, GetZoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetZoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetZoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Zone[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Zone[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetStaffIDWithUserNameCompletedEventHandler(object sender, GetStaffIDWithUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStaffIDWithUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStaffIDWithUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetStaffGroupWithUserNameCompletedEventHandler(object sender, GetStaffGroupWithUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStaffGroupWithUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStaffGroupWithUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AuthenticateTokenCompletedEventHandler(object sender, AuthenticateTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AuthenticateTokenDigipassCompletedEventHandler(object sender, AuthenticateTokenDigipassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateTokenDigipassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateTokenDigipassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ResetTokenCompletedEventHandler(object sender, ResetTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResetTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResetTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetUserAdFullDetailsWLoginNameCompletedEventHandler(object sender, GetUserAdFullDetailsWLoginNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserAdFullDetailsWLoginNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserAdFullDetailsWLoginNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserAdDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserAdDetails)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591